Config = {}

Config.CurrencyIcon = '$' -- CURRENCY ICON FOR NOTIFICATIONS

Config.Price = 5 -- PRICE FOR 1 BULLET

-- LOCATIONS OF THE AMMO BUYING STATIONS (NAMES DONT MAKE ANY DIFFERENCE BUT SHOULDNT BE IDENTICAL)
Config.Locations = {
	['Ammunation'] = {
        coords = vector3(20.1932, -1106.314, 29.79703),
        job = false,
	markerColor = vector3(0, 0, 255),
	markerType = 20,
	markerDensity = 75,
	markerSize = vector3(1.0, 1.0, 1.0),
    },
	['Police'] = {
        coords = vector3(452.0893, -980.1588, 30.68932),
        job = 'police',
	markerColor = vector3(0, 0, 255),
	markerType = 20,
	markerDensity = 75,
	markerSize = vector3(1.0, 1.0, 1.0),
    },
}


-- LIST OF SUPPORTED WEAPONS
Config.Weapons = {
	'weapon_pistol',
	'weapon_pistol_mk2',
	'weapon_combatpistol',
	'weapon_appistol',
	'weapon_stungun',
	'weapon_pistol50',
	'weapon_snspistol',
	'weapon_snspistol_mk2',
	'weapon_heavypistol',
	'weapon_vintagepistol',
	'weapon_flaregun',
	'weapon_marksmanpistol',
	'weapon_revolver',
	'weapon_revolver_mk2',
	'weapon_doubleaction',
	'weapon_raypistol',
	'weapon_ceramicpistol',
	'weapon_navyrevolver',
	'weapon_microsmg',
	'weapon_smg',
	'weapon_smg_mk2',
	'weapon_assaultsmg',
	'weapon_combatpdw',
	'weapon_machinepistol',
	'weapon_minismg',
	'weapon_raycarbine',
	'weapon_pumpshotgun',
	'weapon_pumpshotgun_mk2',
	'weapon_sawnoffshotgun',
	'weapon_assaultshotgun',
	'weapon_bullpupshotgun',
	'weapon_musket',
	'weapon_heavyshotgun',
	'weapon_dbshotgun',
	'weapon_autoshotgun',
	'weapon_assaultrifle',
	'weapon_assaultrifle_mk2',
	'weapon_carbinerifle',
	'weapon_carbinerifle_mk2',
	'weapon_advancedrifle',
	'weapon_specialcarbine',
	'weapon_specialcarbine_mk2',
	'weapon_bullpuprifle',
	'weapon_bullpuprifle_mk2',
	'weapon_compactrifle',
	'weapon_mg',
	'weapon_combatmg',
	'weapon_combatmg_mk2',
	'weapon_gusenberg',
	'weapon_sniperrifle',
	'weapon_heavysniper',
	'weapon_heavysniper_mk2',
	'weapon_marksmanrifle',
	'weapon_marksmanrifle_mk2',
	'weapon_rpg',
	'weapon_grenadelauncher',
	'weapon_grenadelauncher_smoke',
	'weapon_minigun',
	'weapon_firework',
	'weapon_railgun',
	'weapon_hominglauncher',
	'weapon_compactlauncher',
	'weapon_rayminigun',
}
